-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_PRICE
FROM USED_GOODS_BOARD B
INNER JOIN USED_GOODS_USER U ON (B.WRITER_ID = U.USER_ID)
WHERE STATUS = 'DONE'
GROUP BY USER_ID, NICKNAME
HAVING TOTAL_PRICE >= 700000
ORDER BY TOTAL_PRICE;